MyWeb/Controllers/ChessController.cs
using MyWeb.GameChess;
using MyWeb.ViewModel;
using MyWeb.WgStatic;
using System;
using System.IO;
using System.Web.Mvc;

namespace MyWeb.Controllers
{
    public class ChessController : Controller
    {
        // GET: Chess
        [Authorize]
        public ActionResult Index()
        {
            // ip
            string myid = User.Identity.Name;
            //User.Identity.Name;            
            // get game
            ChessContent content = MyStaticObj.GetContent(myid);

            // create game if not exist
            if (content == null)
            {
                content = GetChessContent(Choose.Difficulty.Medium, Chess.PlayerIndex.Bot, myid);
                MyStaticObj.InsertContent(myid, content);
            }

            // create new game if the game was done
            if (content.GetGameBoard().Getwinner() != Chess.PlayerIndex.Empt)
                MyStaticObj.InsertContent(myid, GetChessContent(Choose.Difficulty.Medium, Chess.PlayerIndex.Bot, myid));

            // display game board
            return View(
                "Game",
                new ChessGamingViewModel
                {
                    Board = content.GetGameBoard(),
                    Message = "Welcome",

                });
        }

        [Authorize]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Submit(ChessGamingViewModel collection)
        {
            // get move
            Move playerMove = null;
            try
            {
                playerMove = new Move(collection.Move.FromCoord.Row, collection.Move.FromCoord.Col,
                 collection.Move.ToCoord.Row, collection.Move.ToCoord.Col);
            }
            catch (Exception e)
            {
                return View("Error");
            }

            // get object from Static object
            string myid =  User.Identity.Name;
            ChessContent content = MyStaticObj.GetContent(myid);

            // check if finished first
            bool isFinished = (content.GetGameBoard().Getwinner() != Chess.PlayerIndex.Empt);
            if (isFinished)
            {
                String fileContents = System.IO.File.ReadAllText(Server.MapPath("~/data/startboard.xml"));
                content = GetChessContent(Choose.Difficulty.Difficult, Chess.PlayerIndex.Bot, myid);
                MyStaticObj.InsertContent(myid, content);
            }

            // check if it is a valid move and also move the board
            bool isValid = content.MoveGameBoard(myid, playerMove);

            // check if finish
            isFinished = (content.GetGameBoard().Getwinner() != Chess.PlayerIndex.Empt);

            // computer move if valid and not finished
            StringWriter message = new StringWriter();
            Move compMove = new Move(-1, -1, -1, -1);
            Board board = content.GetGameBoard();

            if (!isValid)
                message.Write("(" + playerMove.FromCoord.Row + ", " + playerMove.FromCoord.Col
                    + ":" + content.GetGameBoard().GetChessName(playerMove.FromCoord.Row, playerMove.FromCoord.Col)
                    + ") to (" + playerMove.ToCoord.Row + ", " + playerMove.ToCoord.Col + ") is an invalid move.");

            if (isValid && !isFinished)
            {
                // make choice and move
                Choice choice = content.CompMakeMove();
                compMove = choice.move;
                message.Write("Computer moved from (" + choice.move.FromCoord.Row + ", " + choice.move.FromCoord.Col
                     + ":" + board.GetChessName(choice.move.FromCoord.Row, choice.move.FromCoord.Col) + ")" +
                   " to (" + choice.move.ToCoord.Row + ", " + choice.move.ToCoord.Col
                    + ":" + board.GetChessName(choice.move.ToCoord.Row, choice.move.ToCoord.Col) + ")"
                   );

                //check if computer won the game
                isFinished = (content.GetGameBoard().Getwinner() != Chess.PlayerIndex.Empt);
            }

            // create message
            if (isFinished)
                message.Write(content.GetGameBoard().Getwinner() + " player has won the game");

            // display game board
            return View(
                "Game",
                new ChessGamingViewModel
                {
                    Board = board,
                    Message = message.ToString(),
                    MyMove = compMove
                });
        }

        [Authorize]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Setting(ChessSettingViewModel chessSetting, FormCollection form)
        {

            ChessContent content = MyStaticObj.GetContent( User.Identity.Name);

            // create object
            Choose.Difficulty diff = (Choose.Difficulty)int.Parse((form["DifficultyChoice"].ToString()));
            Chess.PlayerIndex playerSide = (form["SideChoice"].ToString() == Chess.PlayerIndex.Top.ToString()) ? Chess.PlayerIndex.Top : Chess.PlayerIndex.Bot;

            string myid =  User.Identity.Name;
            content.SetDiff(diff);
            content.SetPlayerSide(playerSide, myid);
            content.SetPlayerSide((playerSide == Chess.PlayerIndex.Top) ? Chess.PlayerIndex.Bot : Chess.PlayerIndex.Top, null);

            // display game board
            return View(
                "Game",
                new ChessGamingViewModel
                {
                    Board = content.GetGameBoard(),
                    Message = "Set to " + playerSide + " and " + diff,
                    MyMove = new Move(-1, -1, -1, -1)
                });
        }

        [Authorize]
        public ActionResult Regret()
        {
            ChessContent content = MyStaticObj.GetContent( User.Identity.Name);
            content.RegretMove();
            content.RegretMove();

            return View(
                "Game",
                 new ChessGamingViewModel
                 {
                     Board = content.GetGameBoard(),
                     Message = "Hi Loser!"
                 });
        }

        [Authorize]
        public ActionResult Restart()
        {
            string myid =  User.Identity.Name;
            ChessContent content = GetChessContent(Choose.Difficulty.Medium, Chess.PlayerIndex.Bot, myid);
            MyStaticObj.InsertContent( User.Identity.Name, content);

            return View(
                "Game",
                 new ChessGamingViewModel
                 {
                     Board = content.GetGameBoard(),
                     Message = "Let's do it again then! I am not afraid!"
                 });
        }

        [Authorize]
        public ActionResult Analyze(string command)
        {
            ChessContent content = MyStaticObj.GetContent( User.Identity.Name);

            switch (command)
            {
                case "up": content.GoUpTree(); break;
                case "dive": content.GoDiveTree(); break;
                default:
                    int index;
                    if (int.TryParse(command, out index)) content.GoDiveTree(index);
                    break;
            }

            return View(
                 new ChessAnalyzeViewModel
                 {
                     MyAnalyzerNode = content.GetAnalyzerTree(),
                     MyBoard = content.GetAnalyzerTree().MyBoard
                 }
                 );
        }

        [NonAction]
        private ChessContent GetChessContent(Choose.Difficulty diff, Chess.PlayerIndex player, string id)
        {
            // display setting
            String fileContents = System.IO.File.ReadAllText(Server.MapPath("~/data/startboard.xml"));
            ChessContent content = new ChessContent(fileContents);
            content.SetDiff(diff);
            content.SetPlayerSide(player, id);

            return content;
        }

    }
}

MyWeb/Views/Chess/Analyze.cshtml
@model MyWeb.ViewModel.ChessAnalyzeViewModel
@{
    ViewBag.Title = "Analyze";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .outer-ul {
        height: 550px;
        width: 10000px;
        overflow-y: auto;
    }
    .inner-ul {
        display: inline;
        list-style-type: none;
        padding-right: 20px;
    }
    .hidden-text{
        display:none;
    }
</style>


<h2>Analyzer</h2>

<div id="chessboard">
    <table>
        <tr> @*LEFT*@
            <th>
                @*Button that is used to go to another page*@
                <input type="button" onclick="location=href='@Url.Action("Analyze","Chess", new { command = "up" } )'" value="Up" class="btn-group-sm" />
                <input type="button" onclick="location=href='@Url.Action("Analyze","Chess", new { command = "dive" })'" value="Dive" class="btn-group-sm" />
            </th>
        </tr>

        <tr>
            <th> @Html.Partial("Board", new MyWeb.ViewModel.ChessGamingViewModel() { Board = Model.MyBoard } )</th>
            <th>
                @{

                    try
                    {

                        var chosen = Model.MyAnalyzerNode.GetChosenChild();
                        <p>
                            My Chosen: (@chosen.UpLayerMove.FromCoord.Row ,@chosen.UpLayerMove.FromCoord.Col: @GetChessRoleCode(chosen.UpLayerMove.FromChess.Role))->
                            (@chosen.UpLayerMove.ToCoord.Row, @chosen.UpLayerMove.ToCoord.Col: @GetChessRoleCode(chosen.UpLayerMove.ToChess.Role)):
                            (@GetChessPlayerCode(chosen.MyChoice.winner), @chosen.MyChoice.boardValue.Topval, @chosen.MyChoice.boardValue.Botval, @chosen.MyChoice.boardValue.GetScore())
                        </p>
                    }catch(Exception e)
                    {
                        <p>Bottom Layer</p>
                    }
                }
               

                <ol class="outer-ul" >

                        @for (int i = 0; i < Model.MyAnalyzerNode.GetChildCount(); i++)
                        {
                            var curnode = Model.MyAnalyzerNode.GetIndexedChilden(i);
                            
                              <li>
                                  (@curnode.UpLayerMove.FromCoord.Row ,@curnode.UpLayerMove.FromCoord.Col: @GetChessRoleCode(curnode.UpLayerMove.FromChess.Role))->
                                    (@curnode.UpLayerMove.ToCoord.Row, @curnode.UpLayerMove.ToCoord.Col: @GetChessRoleCode(curnode.UpLayerMove.ToChess.Role)): 
                                     (@GetChessPlayerCode(curnode.MyChoice.winner), @curnode.MyChoice.boardValue.Topval, @curnode.MyChoice.boardValue.Botval, @curnode.MyChoice.boardValue.GetScore())
                                  <input type="button" value="submit" onclick="location.href='@Url.Action("Analyze", "Chess", new { command=i})' " />

                            </li>
                        }
                
                </ol>
            </th>
        </tr>

    </table>
</div>

@{ 
    String GetChessPlayerCode(MyWeb.GameChess.Chess.PlayerIndex player)
    {
        switch (player)
        {
            case MyWeb.GameChess.Chess.PlayerIndex.Top: return "T";
            case MyWeb.GameChess.Chess.PlayerIndex.Bot: return "B";
            case MyWeb.GameChess.Chess.PlayerIndex.Empt: return "E";
            default:return "";
        }
    }

    String GetChessRoleCode(MyWeb.GameChess.Chess.RoleIndex role)
    {
        switch (role)
        {
            case MyWeb.GameChess.Chess.RoleIndex.GENERAL: return "G";
            case MyWeb.GameChess.Chess.RoleIndex.CHARIOT: return "C";
            case MyWeb.GameChess.Chess.RoleIndex.HORSE: return "H";
            case MyWeb.GameChess.Chess.RoleIndex.ARTILLERY: return "A";
            case MyWeb.GameChess.Chess.RoleIndex.ESCORT: return "E";
            case MyWeb.GameChess.Chess.RoleIndex.JUMBO: return "J";
            case MyWeb.GameChess.Chess.RoleIndex.SOLDIER: return "S";
            case MyWeb.GameChess.Chess.RoleIndex.NOTHING: return "";
            default:return "";
        }
    }
}

MyWeb/Views/Chess/Board.cshtml
@model MyWeb.ViewModel.ChessGamingViewModel


<style>
    /* for drawing chess*/
    .board {
        position: absolute;
    }

    .chess {
        position: absolute;
    }
</style>



@*Game board itself*@
<img src="@Url.Content(Model.BoardImages.BoardFile)" width="400" height="600" id="board" />

@for (int i = 0; i < 10; i++)
{
    // generate chess images. They are always anchored on the board after executing the js code
    for (int j = 0; j < 9; j++)
    {
        var myid = i + "-" + j;
        if (Model.Board.GetChessPlayer(i, j).ToString() == "Bot")
        {
            switch (Model.Board.GetChessName(i, j).ToString())
            {
                case "GENERAL":<img src="@Url.Content(Model.BoardImages.BlackGeneralFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />; break;
                case "CHARIOT":<img src="@Url.Content(Model.BoardImages.BlackChariotFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />; break;
                case "HORSE":<img src="@Url.Content(Model.BoardImages.BlackHorseFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />; break;
                case "ARTILLERY":<img src="@Url.Content(Model.BoardImages.BlackArtillaryFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />; break;
                case "ESCORT":<img src="@Url.Content(Model.BoardImages.BlackEscortFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />; break;
                case "JUMBO":<img src="@Url.Content(Model.BoardImages.BlackJumboFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />; break;
                case "SOLDIER":<img src="@Url.Content(Model.BoardImages.BlackSoldierFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />; break;
                default: break;
            }
        }
        else if (Model.Board.GetChessPlayer(i, j).ToString() == "Top")
        {
            switch (Model.Board.GetChessName(i, j).ToString())
            {
                case "GENERAL":<img src="@Url.Content(Model.BoardImages.RedGeneralFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />; break;
                case "CHARIOT":<img src="@Url.Content(Model.BoardImages.RedChariotFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />; break;
                case "HORSE":<img src="@Url.Content(Model.BoardImages.RedHorseFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />; break;
                case "ARTILLERY":<img src="@Url.Content(Model.BoardImages.RedArtillaryFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />; break;
                case "ESCORT":<img src="@Url.Content(Model.BoardImages.RedEscortFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />; break;
                case "JUMBO":<img src="@Url.Content(Model.BoardImages.RedJumboFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />; break;
                case "SOLDIER":<img src="@Url.Content(Model.BoardImages.RedSoldierFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />; break;
                default: break;
            }
        }
        else
        {
            <img src="@Url.Content(Model.BoardImages.BlankFile)" class="chess" id="@myid" onclick="myInteractiveBoard.boardImageClick(id)" />;
        }
    }
}

MyWeb/Views/Chess/Game.cshtml
@model MyWeb.ViewModel.ChessGamingViewModel
@{
    ViewBag.Title = "Game";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    /* for drawing chess*/
    .btnHidden {
        display: none;
    }

    .btnMajor {
        margin: 3px 4px 3px 4px;
        width: 80px;
        height: 30px;
    }
</style>

<h2>Chess</h2>

<div id="chessboard">

    @* Hidden attributes. They are used to store inputs and for giving it back to the server *@
    @using (Html.BeginForm("Submit", "Chess", FormMethod.Post))
    {
        @Html.TextBoxFor(model => model.Move.FromCoord.Row, new { @class = "form-control text-center", @type = "hidden", @id = "Fromrow" });
        @Html.TextBoxFor(model => model.Move.FromCoord.Col, new { @class = "form-control text-center", @type = "hidden", @id = "Fromcol" });
        @Html.TextBoxFor(model => model.Move.ToCoord.Row, new { @class = "form-control text-center", @type = "hidden", @id = "Torow" });
        @Html.TextBoxFor(model => model.Move.ToCoord.Col, new { @class = "form-control text-center", @type = "hidden", @id = "Tocol" });
        <button type="submit" id="btnSubmit" value="Submit" class="btn-primary btnHidden">Submit</button>
    }

    @{
        @Html.TextBoxFor(model => model.MyMove.FromCoord.Row, new { @class = "form-control text-center", @type = "hidden", @id = "CompFromRow" });
        @Html.TextBoxFor(model => model.MyMove.FromCoord.Col, new { @class = "form-control text-center", @type = "hidden", @id = "CompFromCol" });
        @Html.TextBoxFor(model => model.MyMove.ToCoord.Row, new { @class = "form-control text-center", @type = "hidden", @id = "CompToRow" });
        @Html.TextBoxFor(model => model.MyMove.ToCoord.Col, new { @class = "form-control text-center", @type = "hidden", @id = "CompToCol" });
    }

    <table>
        <tr>
            <th>
               @Html.Partial("Board")

            </th>
            <th>
                <p id="message">@Model.Message</p>
                <p> Please select 1) Difficulty; 2) Your chess color</p>
                @{ using (Html.BeginForm("Setting", "Chess", FormMethod.Post))
                    {

                        @Html.DropDownListFor(model => model.DifficultyChoice, new SelectList(Model.DifficultyChoice, "Value", "LevelName"), new { @class = "form-control" })
                        @Html.DropDownListFor(model => model.SideChoice, new SelectList(Model.SideChoice, "Value", "SideName"), new { @class = "form-control" })
                        <button type="submit" id="btnS" value="Submit" class="btn-primary btnMajor">Submit</button>
                    }
                }
                <input type="button" onclick="location=href='@Url.Action("Regret", "Chess")'" value="Regret" class="btn-primary btnMajor" /><br />
                <input type="button" onclick="location=href='@Url.Action("Restart", "Chess")'" value="Restart" class="btn-primary btnMajor" />
            </th>
        </tr>
    </table>



    <script type="text/javascript" src="~/Scripts/WgBoard/board.js"></script>

    <script>

        var myInteractiveBoard = InteractiveBoard();
        
        document.addEventListener("DOMContentLoaded", function (event) {    
            myInteractiveBoard.interactiveBoardInit();
            requestAnimationFrame(mycallback);
        });
        
        window.onresize = function function_reference() {
            myInteractiveBoard.boardResize();
        };

        function mycallback() {
            myInteractiveBoard.boardMovement();
            requestAnimationFrame(mycallback);
        }
    </script>
</div>